language: "go"
go:
  - "1.9"
  - "1.10"
  - "1.11"
before_install:
  - cd ${TRAVIS_HOME}/gopath/src/github.com && mv isLishude islishude
script:
  - go test -v ./...
notifications:
  email:
    on_success: "change"
    on_failure: "always"
